# yamllint disable rule:line-length
---
name: Release
on:
  workflow_call:
    inputs:
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false
      publishToBinaries:
        type: boolean
        description: Flag to enable the publication to binaries
        default: false
        required: false
      binariesS3Bucket:
        type: string
        description: Target bucket
        default: downloads-cdn-eu-central-1-prod
        required: false
      vaultAddr:
        type: string
        description: Custom vault installation
        required: false
      artifactoryRoleSuffix:
        type: string
        description: Artifactory promoter suffix specified in Vault repo config
        default: promoter
        required: false
      mavenCentralSync:
        type: boolean
        description: Enable synchronization to Maven Central
        default: false
        required: false

jobs:[]
